### PR TITLE
Verify all installed packages using rpm -V

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
[test]

**Comment by mfojtik** [comment]
@bparees more here:

```console
package php55-php-pecl-imagick is not installed
package php55-php-pecl-xdebug is not installed
```

@remicollet FYI

**Comment by remicollet** [comment]
Those package are not part of RHSCL, so cannot be installed in the php 5.5 imahe.

**Comment by mfojtik** [comment]
@remicollet ok, thanks, I will remove them then.

**Comment by mfojtik** [comment]
@sdodson @bparees just out of curiosity, do we have those packages in openshift channels? I do remember talking about php something a long time ago. I think we should remove them from the centos image as they don't exists in centos scl, but I wonder if they exists in our channels.

**Comment by mfojtik** [comment]
@remicollet how about php-5.6

**Comment by remicollet** [comment]
5.6 (in RHSCL) only have Xdebug, no imagick.

**Pull request closed without merging**
