### PR TITLE
Pass all env to apache

### PR DESCRIPTION
**Pull request by mfojtik**
Fixes: https://github.com/openshift/sti-php/issues/83

@bparees @remicollet is this sane? (we pass all env in other images, so php should not be special here). This will allow users to do $_ENV

### CODE REVIEW

**Comment by remicollet** [comment]
Why all ENV would have to be available in Apache sub process ?

**Comment by mfojtik** [comment]
@remicollet the original issue was about user trying to do:

```php
print "env is: ".$_ENV["USER"]."\n";
```

Which printed nothing. Then the user set a TESTVAR variable for container and that variable was empty as well. The mystery for me is how the other variables (like MYSQL one) get passed to PHP :-)

**Comment by bparees** [comment]
Given we're already doing similar things elsewhere (https://github.com/openshift/sti-perl/blob/master/5.20/s2i/bin/run#L13-L15) i'm ok with this, but will wait for @remicollet to sign off or suggest an alternative as well.

**Comment by mfojtik** [comment]
@bparees updated this PR to include 5.5 image + made it in sync with perl awk approach

**Comment by bparees** [comment]
lgtm

**Comment by mfojtik** [comment]
@remicollet you OK merging this?

**Comment by hanzz** [comment]
I see the use-case here that sti-php user wants to be able to configure PHP app running in container using the ENV variables. I think that's quite easy way how to do that.

My concerns are that passing all env variables could mean passing also possible secret variables which could be later read by some 3rd person using some bug in PHP code.

I know there are [Secrets](https://docs.openshift.com/enterprise/3.0/dev_guide/secrets.html) and probably similar stuff in Openshift, so if you really believe all the people will use it with sti-php, I think it's safe to merge, otherwise I would think about different solutions to this problem.

**Comment by remicollet** [comment]
Yes, not passing environment variables to apache modules and sub-process is a standard Apache feature (and reason for SetEnv directive)

So exposing "everything", without any filter, seems terrible strange.

I will definitively prefer "any" other solution.
At least, an option with the list of variable to expose this way (ex all variables set, and used by the "envsubst" command have no need to be exposed)

**Comment by mfojtik** [comment]
@remicollet just brainstorming:

1) we can whitelist only env vars with HTTP_ prefix?
2) we can filter out all system env and pass only user set properties (that will be pretty hard to do)
3) we can have special env var where you list envs you want to pass (that seems terrible user experience)
4) we let you write your own env.conf (which I think is already possible to override with assemble script now).

**Comment by hanzz** [comment]
I think allowing prefixed variables seems to be a good way. We can also show some kind of warning with a list of variables passed to PHP in the run script. Something like:

```
Following environment variables are passed to all PHP scripts executed by Apache httpd:
    -  ...
Make sure they are not containing sensitive data.
```

**Comment by mfojtik** [comment]
@hanzz yes, I saw it. it is because awk does not filter these... I had for loop there but it was pretty ugly ;-)
Also we have already in sti-perl (assuming that image is broken now :)

**Comment by mfojtik** [comment]
@hanzz @remicollet now what you suggest the prefix should be? `HTTP_` ? `PHP_` ?

**Comment by bparees** [comment]
@mfojtik @hanzz @remicollet bump

**Comment by remicollet** [comment]
I think adding new ENV for each need is going to be a nightmare...
I think PR #67 will have fix this issue and TZ one.

**Comment by mfojtik** [comment]
@bparees I incline to close this PR till we figure out how we want to deliver envs to PHP. Also since there are no other bugs open for things like database envs I would prefer to wait till someone other than me complains :-)

**Pull request closed without merging**
