### PR TITLE
remove pecl as it is not signed

### PR DESCRIPTION
**Pull request by bparees**

### CODE REVIEW

**Comment by bparees** [comment]
@brenton @mfojtik will need to look into this later but i'm removing it so we can successfully build again for now.

**Comment by bparees** [comment]
@brenton looks like the issue is that since you added the pecl rpm to li, we're picking it up from there but the package is not signed.  Is there something you need to to do to get it signed, or should i be editing our dockerfile to trust it unsigned?

**Comment by bparees** [comment]
(or is there a cert I need to add to our dockerfile?)

**Comment by brenton** [comment]
I'm working to get them signed this morning.  Sorry about that!

**Pull request merged**
